services:
  navidrome:
    image: docker.io/deluan/navidrome:latest
    user: 1000:1000 # should be owner of volumes
    ports:
      - "4533:4533"
    restart: unless-stopped
    environment:
      # Optional: put your config options customization here. Examples:
      # ND_LOGLEVEL: debug
    volumes:
      - "/var/lib/navidrome:/data"
      - "/mnt/seagate/Music:/music:ro"
